# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e651f3405f72b9d4fe58311be341b102ac0c54f317c13fae53d63a84857e8d6f8b396549d29849b30c7e572c8cd0760608f7a1c8a5cd58241b18d836fd2b229a

test:
  secret_key_base: c7cdc950a923187bd269505fe3d3e96397d4f30e0342b652810d31e9a08e19e85ba6635aa0803d4efdd442522c1ab1c31c6bcc4fcacda891b13e7b3a524790ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
